### ISSUE TITLE
Duplicate Displays render same image

### ISSUE THREAD

**Issue by VegaDeftwing** [letoram/arcan#196] opened 2020-09-14 03:38 UTC
Not sure if this should be an Arcan or Durden issue:
I have 3 displays on my setup, all 4k. Two of the monitors are identical, including their edid (as verified in ```/sys/devices/pci0000:00/[...]/drm/card0/card0-DP-3``` ) It's these two with the duplicate edid that are acting funny- in Durden they both render the same image while the 3rd, slightly different display, does correctly get assigned its own view. When using the 'global menu' in Durden to configure the displays the common name of the display is only listed once. I realize this may be hardware and os specific to some extent. I'm on Arch Linux 5.8.8, GPU is an AMD VEGA56
Arcan commit 496603deda8a2970410c710501fab661bd72308e (September 8th)
Durden commit cfd7c42f53fc8468869be547ce4e261618c43600 (September 10th)
Let me know if you need any more information.

**Comment by letoram** [comment] 2020-09-14 10:00
This is a fun one and lies between durden and arcan actually, but the part you are experiencing is in durden. Its display management code can't really understand when there are duplicate displays - even if the other parts of the EDID are similar, the serial number part should be different no? do you manually patch/override them or is it actually like that?

It's not a hard fix (i.e. cheat on collision and give the duplicate a new/random serial), but since there is no reliable identifier, if you unplug both of them and replugs into different connectors they won't get the right workspaces back.

The other part of the same code where this can happen is basically when doing a system/reset (that I can reproduce here) and some drivers/time-of-day/cables/bad code we can't retrieve the EDID and durden just assigns it something, fingers crossed.

**Comment by VegaDeftwing** [comment] 2020-09-14 14:48
>  the serial number part should be different no? do you manually patch/override them or is it actually like that?

I never manually patched anything, but they are cheap Monoprice monitors.
When I submitted this issue I failed to mention that just running ```arcan welcome``` actually does output on one of these monitors but not the other, so I guess that does confirm it's a durden thing.

**Comment by letoram** [comment] 2020-09-14 16:58
Durden's multidisplay management was the testing ground for how that should work - it is scheduled (albeit a bit down) for a rehaul and then merged as a support script that arcan has in its base distribution.

There is fluctuation in the low level interfaces for GPU hotplug, HDR, VFR and more VR displays that might affect the design, hence why I am waiting. In the meantime I will push some workaround that deals with these kinds of collisions and some related things.

**Comment by letoram** [comment] 2020-12-21 10:40
The workarounds should be present in Durden 0.6, with some caveats around power-state off all displays and re-enabling them (ordering might get confused). Any further issues with this one should be in Durden though.

**Closed by letoram** 2020-12-21 10:40 UTC
Labels: confirmed
